#!/bin/env python 
n=2
while 1 :
    i=0;
    while i<=10:
	print ('%d X %d = %d'%(n,i,n*i))
        i = i+1;
    choice=int(input("if u next table ,then press 1 othrwise press 0: "))
    if choice == 0:
        break
    n=n+1;
