#!/bin/env python
emp = {"name":"KIRAN","age":24,"company":"SAP","native":"KARNATAKA","qualification":"B.TECH","branch":"MECHANICAL","percentage":78}
#print (emp)

print ("name      : %s" %emp["name"])
print ("age       : %d" %emp["age"])
print ("company   : %s" %emp["company"])
print ("native    : %s" %emp["native"])
print ("branch    : %s" %emp["branch"])
print ("percentage: %d" %emp["percentage"])

for x in emp.items():
	print(x)
